language: python

addons:
  apt:
    packages:
      - bash
      - dash
      - zsh

# whatever the current shebang, replace with hardcoded shell
script: >
  sed -i '1s@.*@#!!/usr/bin/env ksh@' json.ksh && ./all-tests.sh &&
  sed -i '1s@.*@#!/usr/bin/env bash@' json.ksh && ./all-tests.sh &&
  sed -i '1s@.*@#!/usr/bin/env zsh@'  json.ksh && ./all-tests.sh &&
  sed -i '1s@.*@#!/usr/bin/env dash@' json.ksh && ./all-tests.sh
